name: backend countinuous integration
on:
  workflow_dispatch: 

  # push:
  #   branches: [ "feature_test" ]

  pull_request:
    types:
      - opened 
    branches:
      - main
    paths:
      - starter/frontend/**

jobs:
  run_test:
    name: Run test
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend

    steps:
      # Check out the code to the runner
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6' 
      
      - name: Install dependencies
        run: |
          sudo pip install pipenv
          pip install pytest
          pip install flask
          pip install -U flask-cors
          # which pytest

      - name: Run test
        run: |
          pipenv run test
          # FAIL_TEST=true pipenv run test  # Test fail
        # run: python -m unittest discover

  run_lint:
    name: Run lint
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend

    steps:
      # Check out the code to the runner
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6' 
      
      - name: Install dependencies
        run: |
          sudo pip install pipenv
          python3 -m pip install flake8
          # which flake8

      - name: Run lint
        run: |
          pipenv run lint
          # pipenv run lint-fail  # Test Lint fail

      # - name: flake8 Lint - good
      #   uses: py-actions/flake8@v2
      #   with:
      #     ignore: "E501"
      #     max-line-length: "100"

  build:
    name: Run build
    needs: [run_lint, run_test]
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend

    steps:
      # Check out the code to the runner
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run application
        run: |
          echo "Backend URL is ${{ vars.REACT_APP_MOVIE_API_URL }}"
          docker build --tag mp-backend:latest .    # Build the image
          docker run -p 5000:5000 --name mp-backend -d mp-backend   # Run the image
          curl http://localhost:5000/movies
          # docker logs -f mp-backend
