name: Frontend countinuous integration
on:
  workflow_dispatch: 
  # push: 
  #   branches:
  #     - main

# env:
#   AWS_REGION: us-east-1     # Update this to your AWS Region
#   TF_ACTION_WORKING_DIR: 'terraform' # Update this to your Terraform files directory

jobs:
  deploy_k8s:
    name: 'Deploy to ECR'
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner

    steps:
      # Check out the code to the runner
      - name: Checkout
        uses: actions/checkout@v3
      
