name: Frontend countinuous integration
on:
  workflow_dispatch: 
  push: 
    branches:
      - main
  # pull_request:
  #   types:
  #     - opened 
  #   branches:
  #     - main
  #   paths:
  #     - starter/frontend/**

# env:
#   AWS_REGION: us-east-1     # Update this to your AWS Region
#   TF_ACTION_WORKING_DIR: 'terraform' # Update this to your Terraform files directory

jobs:
  run_lint:
    name: Run lint
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner
    defaults:
      run:
        shell: bash
        working-directory: ./starter/frontend

    steps:
      # Check out the code to the runner
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install the dependencies
        run: npm ci