name: Frontend Continuous Integration

on:
  workflow_dispatch: 
  pull_request:
    types:
      - opened 
    branches:
      - main
    # paths:
    #   - starter/frontend/**

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner
    defaults:
      run:
        shell: bash
        working-directory: ./starter/frontend

    steps:
      # Check out the code to the runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: 'npm'  # Perform a cache action to restore cache before dependency install
          cache-dependency-path: starter/frontend/package-lock.json
        
      - name: Install the dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint

  test:
    name: Run test
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner
    defaults:
      run:
        shell: bash
        working-directory: ./starter/frontend

    steps:
      - name: Checkout the code to the runner
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: 'npm'  # Perform a cache action to restore cache before dependency install
          cache-dependency-path: starter/frontend/package-lock.json
          
      - name: Install the dependencies
        run: npm ci

      - name: Run test
        run: npm run test

  build:
    name: Run build
    needs: [lint, test]
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./starter/frontend

    steps:
      - name: Checkout the code to the runner
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: 'npm'  # Perform a cache action to restore cache before dependency install
          cache-dependency-path: starter/frontend/package-lock.json
          
      - name: Install the dependencies
        run: npm ci

      - name: Run test
        run: npm run test
