name: Test Variables
on: push
env:
  mascot: Mona
  super_duper_var: totally_awesome

jobs:
  windows_job:
    runs-on: windows-latest
    environment: Production
    steps:
      - run: echo 'Hi ${{ env.mascot }} ${{ vars.Production.REACT_APP_MOVIE_API_URL }}'  # Hi Mona
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Octocat
        env:
          mascot: Octocat
  linux_job:
    runs-on: ubuntu-latest
    environment: Production
    env:
      mascot: Tux
    steps:
      - run: |
            echo 'Hi ${{ env.mascot }}'  # Hi Tux
            echo "$ALLMYSECRETS"
            echo "$ALLMYVARS"
        shell: bash
        env:
            ALLMYSECRETS: ${{ toJSON(secrets) }}
            ALLMYVARS: ${{ toJSON(vars) }}
